import type { World, Puzzle } from "./game-types"

const sequentialPuzzles: Puzzle[] = [
  {
    id: "seq-1",
    title: "Morning Routine",
    description: "Help the robot get ready for the day by putting the steps in order.",
    story: "RoboHelper needs to start its day, but its instruction manual got scrambled! Put the steps in the right order so it can get ready.",
    difficulty: "beginner",
    category: "sequential",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["action"], correctPieceId: "wake-up", placedPieceId: null, hint: "What happens first when you wake up?" },
      { id: "slot-2", position: 1, acceptsType: ["action"], correctPieceId: "brush-teeth", placedPieceId: null, hint: "Time for dental hygiene!" },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "eat-breakfast", placedPieceId: null, hint: "Fuel up for the day!" },
      { id: "slot-4", position: 3, acceptsType: ["action"], correctPieceId: "go-to-work", placedPieceId: null, hint: "Ready to start the day!" },
    ],
    availablePieces: [
      { id: "eat-breakfast", type: "action", label: "Eat Breakfast", description: "Have a healthy meal", color: "bg-chart-1", icon: "UtensilsCrossed" },
      { id: "go-to-work", type: "action", label: "Go to Work", description: "Head out the door", color: "bg-chart-1", icon: "Briefcase" },
      { id: "wake-up", type: "action", label: "Wake Up", description: "Open your eyes and get out of bed", color: "bg-chart-1", icon: "Sun" },
      { id: "brush-teeth", type: "action", label: "Brush Teeth", description: "Clean those pearly whites", color: "bg-chart-1", icon: "Sparkles" },
    ],
    expectedOutput: "Wake Up -> Brush Teeth -> Eat Breakfast -> Go to Work",
    hints: [
      "Think about what you do first thing in the morning.",
      "You need to be awake before you can do anything else!",
      "The correct order is: Wake, Hygiene, Eat, Leave.",
    ],
    xpReward: 50,
    conceptTaught: "Sequential Execution",
  },
  {
    id: "seq-2",
    title: "Recipe Builder",
    description: "Arrange the cooking steps to make a perfect sandwich.",
    story: "Chef Bot found a recipe, but the steps are mixed up! Help arrange them in the right order to make a delicious sandwich.",
    difficulty: "beginner",
    category: "sequential",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["action"], correctPieceId: "get-bread", placedPieceId: null, hint: "Every sandwich starts with this" },
      { id: "slot-2", position: 1, acceptsType: ["action"], correctPieceId: "add-filling", placedPieceId: null, hint: "The good stuff goes in the middle" },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "add-topping", placedPieceId: null, hint: "A finishing touch on top" },
      { id: "slot-4", position: 3, acceptsType: ["action"], correctPieceId: "close-sandwich", placedPieceId: null, hint: "Seal it up!" },
    ],
    availablePieces: [
      { id: "close-sandwich", type: "action", label: "Close Sandwich", description: "Put the top slice on", color: "bg-chart-1", icon: "Layers" },
      { id: "add-filling", type: "action", label: "Add Filling", description: "Place cheese and ham", color: "bg-chart-1", icon: "Plus" },
      { id: "get-bread", type: "action", label: "Get Bread", description: "Take out two slices of bread", color: "bg-chart-1", icon: "Square" },
      { id: "add-topping", type: "action", label: "Add Topping", description: "Lettuce and tomato", color: "bg-chart-1", icon: "Leaf" },
    ],
    expectedOutput: "Get Bread -> Add Filling -> Add Topping -> Close Sandwich",
    hints: [
      "You need a base before adding anything.",
      "Fillings go before toppings.",
      "The last step closes everything up.",
    ],
    xpReward: 50,
    conceptTaught: "Sequential Execution",
  },
  {
    id: "seq-3",
    title: "Space Launch",
    description: "Prepare the rocket for launch with the correct sequence.",
    story: "Mission Control needs you! The launch sequence got jumbled. Put the steps in the right order to send the rocket to space safely!",
    difficulty: "intermediate",
    category: "sequential",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["action"], correctPieceId: "fuel-rocket", placedPieceId: null },
      { id: "slot-2", position: 1, acceptsType: ["action"], correctPieceId: "check-systems", placedPieceId: null },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "countdown", placedPieceId: null },
      { id: "slot-4", position: 3, acceptsType: ["action"], correctPieceId: "ignite-engines", placedPieceId: null },
      { id: "slot-5", position: 4, acceptsType: ["action"], correctPieceId: "liftoff", placedPieceId: null },
    ],
    availablePieces: [
      { id: "liftoff", type: "action", label: "Liftoff!", description: "We have liftoff!", color: "bg-chart-1", icon: "Rocket" },
      { id: "countdown", type: "action", label: "Countdown", description: "10, 9, 8...", color: "bg-chart-1", icon: "Timer" },
      { id: "fuel-rocket", type: "action", label: "Fuel Rocket", description: "Fill the tanks with fuel", color: "bg-chart-1", icon: "Fuel" },
      { id: "check-systems", type: "action", label: "Check Systems", description: "All systems go?", color: "bg-chart-1", icon: "CheckCircle" },
      { id: "ignite-engines", type: "action", label: "Ignite Engines", description: "Start the rocket engines", color: "bg-chart-1", icon: "Flame" },
    ],
    expectedOutput: "Fuel Rocket -> Check Systems -> Countdown -> Ignite Engines -> Liftoff!",
    hints: [
      "You need fuel before you can do anything else.",
      "Always check systems before the countdown begins.",
      "Engines ignite right before liftoff.",
    ],
    xpReward: 75,
    conceptTaught: "Sequential Execution & Planning",
  },
]

const conditionalPuzzles: Puzzle[] = [
  {
    id: "cond-1",
    title: "Weather Bot",
    description: "Help the robot decide what to wear based on the weather.",
    story: "WeatherBot checks the sky every morning but forgot its decision logic. Help it figure out what to wear!",
    difficulty: "beginner",
    category: "conditional",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["condition"], correctPieceId: "check-rain", placedPieceId: null, hint: "First, check the condition" },
      { id: "slot-2", position: 1, acceptsType: ["action"], correctPieceId: "take-umbrella", placedPieceId: null, hint: "What to do if it IS raining?" },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "wear-sunglasses", placedPieceId: null, hint: "What to do if it is NOT raining?" },
    ],
    availablePieces: [
      { id: "wear-sunglasses", type: "action", label: "Wear Sunglasses", description: "For sunny days", color: "bg-chart-1", icon: "Sun" },
      { id: "check-rain", type: "condition", label: "IF Raining?", description: "Check the weather", color: "bg-accent", icon: "CloudRain" },
      { id: "take-umbrella", type: "action", label: "Take Umbrella", description: "Stay dry!", color: "bg-chart-1", icon: "Umbrella" },
    ],
    expectedOutput: "IF Raining? -> THEN Take Umbrella -> ELSE Wear Sunglasses",
    hints: [
      "Conditions always come first - you check BEFORE you decide.",
      "The THEN branch is what happens when the condition is TRUE.",
      "The ELSE branch handles the opposite case.",
    ],
    xpReward: 75,
    conceptTaught: "If-Then-Else Logic",
  },
  {
    id: "cond-2",
    title: "Grade Calculator",
    description: "Build the logic to assign letter grades based on scores.",
    story: "The school's grading computer crashed! Rebuild its logic to assign the right grades.",
    difficulty: "intermediate",
    category: "conditional",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["condition"], correctPieceId: "check-90", placedPieceId: null, hint: "Check the highest grade first" },
      { id: "slot-2", position: 1, acceptsType: ["value"], correctPieceId: "grade-a", placedPieceId: null, hint: "What grade for 90+?" },
      { id: "slot-3", position: 2, acceptsType: ["condition"], correctPieceId: "check-70", placedPieceId: null, hint: "Check the next threshold" },
      { id: "slot-4", position: 3, acceptsType: ["value"], correctPieceId: "grade-b", placedPieceId: null, hint: "What grade for 70-89?" },
      { id: "slot-5", position: 4, acceptsType: ["value"], correctPieceId: "grade-c", placedPieceId: null, hint: "What about everyone else?" },
    ],
    availablePieces: [
      { id: "grade-b", type: "value", label: "Grade: B", description: "Good job!", color: "bg-chart-3", icon: "Award" },
      { id: "check-70", type: "condition", label: "IF Score >= 70", description: "Check for B grade", color: "bg-accent", icon: "GitBranch" },
      { id: "grade-a", type: "value", label: "Grade: A", description: "Excellent!", color: "bg-chart-3", icon: "Trophy" },
      { id: "grade-c", type: "value", label: "Grade: C", description: "Keep trying!", color: "bg-chart-3", icon: "ThumbsUp" },
      { id: "check-90", type: "condition", label: "IF Score >= 90", description: "Check for A grade", color: "bg-accent", icon: "GitBranch" },
    ],
    expectedOutput: "IF Score >= 90 -> Grade: A -> ELSE IF Score >= 70 -> Grade: B -> ELSE Grade: C",
    hints: [
      "Check the highest threshold first.",
      "Each condition filters scores into groups.",
      "The final value catches everything that didn't match above.",
    ],
    xpReward: 100,
    conceptTaught: "Chained Conditionals",
  },
]

const loopPuzzles: Puzzle[] = [
  {
    id: "loop-1",
    title: "Star Printer",
    description: "Use a loop to print a row of stars.",
    story: "ArtBot wants to draw a line of 5 stars. Instead of placing each one by hand, teach it to use a loop!",
    difficulty: "beginner",
    category: "loops",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "set-counter", placedPieceId: null, hint: "Start by setting up a counter" },
      { id: "slot-2", position: 1, acceptsType: ["loop"], correctPieceId: "repeat-5", placedPieceId: null, hint: "How many times should we repeat?" },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "print-star", placedPieceId: null, hint: "What action repeats each time?" },
    ],
    availablePieces: [
      { id: "print-star", type: "action", label: "Print Star", description: "Output one star", color: "bg-chart-1", icon: "Star" },
      { id: "repeat-5", type: "loop", label: "REPEAT 5 Times", description: "Do something 5 times", color: "bg-chart-4", icon: "Repeat" },
      { id: "set-counter", type: "value", label: "Counter = 0", description: "Initialize the counter", color: "bg-chart-3", icon: "Hash" },
    ],
    expectedOutput: "Counter = 0 -> REPEAT 5 Times { Print Star }",
    hints: [
      "Loops need a starting point - initialize first!",
      "The REPEAT block wraps around the action.",
      "The action inside the loop runs 5 times.",
    ],
    xpReward: 75,
    conceptTaught: "Basic Loops",
  },
  {
    id: "loop-2",
    title: "Number Cruncher",
    description: "Sum all numbers from 1 to 10 using a loop.",
    story: "MathBot needs to add up numbers from 1 to 10. Build a loop that accumulates the total!",
    difficulty: "intermediate",
    category: "loops",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "set-sum", placedPieceId: null },
      { id: "slot-2", position: 1, acceptsType: ["loop"], correctPieceId: "for-1-to-10", placedPieceId: null },
      { id: "slot-3", position: 2, acceptsType: ["operator"], correctPieceId: "add-to-sum", placedPieceId: null },
      { id: "slot-4", position: 3, acceptsType: ["action"], correctPieceId: "show-result", placedPieceId: null },
    ],
    availablePieces: [
      { id: "show-result", type: "action", label: "Show Total", description: "Display the sum", color: "bg-chart-1", icon: "Eye" },
      { id: "for-1-to-10", type: "loop", label: "FOR i = 1 TO 10", description: "Loop through numbers", color: "bg-chart-4", icon: "Repeat" },
      { id: "add-to-sum", type: "operator", label: "Sum = Sum + i", description: "Add current number", color: "bg-chart-5", icon: "Plus" },
      { id: "set-sum", type: "value", label: "Sum = 0", description: "Start with zero", color: "bg-chart-3", icon: "Hash" },
    ],
    expectedOutput: "Sum = 0 -> FOR i = 1 TO 10 { Sum = Sum + i } -> Show Total (55)",
    hints: [
      "Initialize the accumulator before the loop.",
      "The loop variable i goes from 1 to 10.",
      "After the loop, display the result.",
    ],
    xpReward: 100,
    conceptTaught: "Loop Accumulation",
  },
]

const patternPuzzles: Puzzle[] = [
  {
    id: "pat-1",
    title: "Signal Decoder",
    description: "Find the pattern in the signal and complete the sequence.",
    story: "Incoming transmission detected! The signal follows a pattern, but it's incomplete. Can you figure out what comes next?",
    difficulty: "beginner",
    category: "patterns",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "val-2", placedPieceId: null, hint: "Look at the pattern: 2, 4, 6, ..." },
      { id: "slot-2", position: 1, acceptsType: ["value"], correctPieceId: "val-4", placedPieceId: null },
      { id: "slot-3", position: 2, acceptsType: ["value"], correctPieceId: "val-6", placedPieceId: null },
      { id: "slot-4", position: 3, acceptsType: ["value"], correctPieceId: "val-8", placedPieceId: null, hint: "Adding 2 each time..." },
    ],
    availablePieces: [
      { id: "val-6", type: "value", label: "6", description: "The number 6", color: "bg-chart-3", icon: "Hash" },
      { id: "val-8", type: "value", label: "8", description: "The number 8", color: "bg-chart-3", icon: "Hash" },
      { id: "val-2", type: "value", label: "2", description: "The number 2", color: "bg-chart-3", icon: "Hash" },
      { id: "val-4", type: "value", label: "4", description: "The number 4", color: "bg-chart-3", icon: "Hash" },
    ],
    expectedOutput: "2, 4, 6, 8 (even numbers / +2 pattern)",
    hints: [
      "Each number is larger than the one before.",
      "The difference between consecutive numbers is always the same.",
      "Add 2 each time: 2, 4, 6, 8.",
    ],
    xpReward: 50,
    conceptTaught: "Pattern Recognition",
  },
  {
    id: "pat-2",
    title: "Boolean Gatekeeper",
    description: "Complete the truth table for logical AND.",
    story: "The Logic Gate is broken! Fill in the correct outputs for the AND gate to restore power to the circuit.",
    difficulty: "intermediate",
    category: "patterns",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "false-1", placedPieceId: null, hint: "TRUE AND FALSE = ?" },
      { id: "slot-2", position: 1, acceptsType: ["value"], correctPieceId: "false-2", placedPieceId: null, hint: "FALSE AND TRUE = ?" },
      { id: "slot-3", position: 2, acceptsType: ["value"], correctPieceId: "true-1", placedPieceId: null, hint: "TRUE AND TRUE = ?" },
      { id: "slot-4", position: 3, acceptsType: ["value"], correctPieceId: "false-3", placedPieceId: null, hint: "FALSE AND FALSE = ?" },
    ],
    availablePieces: [
      { id: "true-1", type: "value", label: "TRUE", description: "Boolean true", color: "bg-chart-4", icon: "Check" },
      { id: "false-1", type: "value", label: "FALSE", description: "Boolean false", color: "bg-chart-3", icon: "X" },
      { id: "false-2", type: "value", label: "FALSE", description: "Boolean false", color: "bg-chart-3", icon: "X" },
      { id: "false-3", type: "value", label: "FALSE", description: "Boolean false", color: "bg-chart-3", icon: "X" },
    ],
    expectedOutput: "AND: (T,F)=F, (F,T)=F, (T,T)=T, (F,F)=F",
    hints: [
      "AND only returns TRUE when BOTH inputs are TRUE.",
      "If either input is FALSE, the result is FALSE.",
      "Only one combination gives TRUE.",
    ],
    xpReward: 100,
    conceptTaught: "Boolean Logic (AND)",
  },
]

const dataFlowPuzzles: Puzzle[] = [
  {
    id: "df-1",
    title: "Data Pipeline",
    description: "Transform a list of numbers through a series of operations.",
    story: "DataBot receives raw numbers and needs to process them. Build the pipeline by placing the correct operations in order!",
    difficulty: "intermediate",
    category: "data-flow",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "input-list", placedPieceId: null, hint: "Start with the raw data" },
      { id: "slot-2", position: 1, acceptsType: ["operator"], correctPieceId: "filter-evens", placedPieceId: null, hint: "Remove unwanted items first" },
      { id: "slot-3", position: 2, acceptsType: ["operator"], correctPieceId: "double-values", placedPieceId: null, hint: "Transform what's left" },
      { id: "slot-4", position: 3, acceptsType: ["action"], correctPieceId: "output-result", placedPieceId: null, hint: "Show the final result" },
    ],
    availablePieces: [
      { id: "double-values", type: "operator", label: "Double Each", description: "Multiply each by 2", color: "bg-chart-5", icon: "ArrowUp" },
      { id: "input-list", type: "value", label: "[1,2,3,4,5]", description: "Input numbers", color: "bg-chart-3", icon: "List" },
      { id: "output-result", type: "action", label: "Output Result", description: "Display final list", color: "bg-chart-1", icon: "Monitor" },
      { id: "filter-evens", type: "operator", label: "Keep Evens", description: "Filter to even numbers only", color: "bg-chart-5", icon: "Filter" },
    ],
    expectedOutput: "[1,2,3,4,5] -> Keep Evens [2,4] -> Double Each [4,8] -> Output",
    hints: [
      "Input data comes first.",
      "Filter before you transform - it's more efficient!",
      "The pipeline processes data step by step.",
    ],
    xpReward: 100,
    conceptTaught: "Data Transformation Pipelines",
  },
]

const debugPuzzles: Puzzle[] = [
  {
    id: "debug-1",
    title: "The Infinite Loop",
    description: "Find and fix the bug causing an infinite loop.",
    story: "Oh no! Someone wrote a loop that never ends. The robot is stuck running in circles! Find the missing piece to fix it.",
    difficulty: "intermediate",
    category: "debugging",
    slots: [
      { id: "slot-1", position: 0, acceptsType: ["value"], correctPieceId: "init-i", placedPieceId: null, hint: "Initialize the counter" },
      { id: "slot-2", position: 1, acceptsType: ["condition"], correctPieceId: "while-less-5", placedPieceId: null, hint: "When should the loop stop?" },
      { id: "slot-3", position: 2, acceptsType: ["action"], correctPieceId: "print-i", placedPieceId: null, hint: "Do something with i" },
      { id: "slot-4", position: 3, acceptsType: ["operator"], correctPieceId: "increment-i", placedPieceId: null, hint: "This piece was MISSING - the bug!" },
    ],
    availablePieces: [
      { id: "increment-i", type: "operator", label: "i = i + 1", description: "THE FIX: Increment the counter!", color: "bg-chart-5", icon: "Plus" },
      { id: "while-less-5", type: "condition", label: "WHILE i < 5", description: "Loop while condition true", color: "bg-accent", icon: "Repeat" },
      { id: "init-i", type: "value", label: "i = 0", description: "Start counter at zero", color: "bg-chart-3", icon: "Hash" },
      { id: "print-i", type: "action", label: "Print i", description: "Show current value", color: "bg-chart-1", icon: "MessageSquare" },
    ],
    expectedOutput: "i=0 -> WHILE i<5 { Print i, i=i+1 } -> Prints: 0,1,2,3,4",
    hints: [
      "A WHILE loop needs something to eventually make the condition FALSE.",
      "If the counter never changes, the loop runs forever!",
      "Add an increment to fix the infinite loop.",
    ],
    xpReward: 125,
    conceptTaught: "Debugging Infinite Loops",
  },
]

export const WORLDS: World[] = [
  {
    id: "sequential",
    name: "Sequence Island",
    description: "Master the art of putting instructions in the right order. Every program starts with a sequence!",
    color: "bg-chart-1",
    icon: "ArrowRight",
    requiredLevel: 1,
    puzzles: sequentialPuzzles,
    category: "sequential",
  },
  {
    id: "conditional",
    name: "Decision Forest",
    description: "Learn to make choices with IF-THEN-ELSE logic. Branch your way through the forest of decisions!",
    color: "bg-accent",
    icon: "GitBranch",
    requiredLevel: 2,
    puzzles: conditionalPuzzles,
    category: "conditional",
  },
  {
    id: "loops",
    name: "Loop Canyon",
    description: "Discover loops - the programmer's power tool for repetition. Why do it once when you can loop?",
    color: "bg-chart-4",
    icon: "Repeat",
    requiredLevel: 3,
    puzzles: loopPuzzles,
    category: "loops",
  },
  {
    id: "patterns",
    name: "Pattern Peaks",
    description: "Sharpen your eyes to spot patterns in data. Recognizing patterns is the foundation of great algorithms!",
    color: "bg-chart-3",
    icon: "Puzzle",
    requiredLevel: 4,
    puzzles: patternPuzzles,
    category: "patterns",
  },
  {
    id: "data-flow",
    name: "Data Stream",
    description: "Watch data flow and transform. Learn how information moves through a program step by step.",
    color: "bg-chart-5",
    icon: "Workflow",
    requiredLevel: 5,
    puzzles: dataFlowPuzzles,
    category: "data-flow",
  },
  {
    id: "debugging",
    name: "Bug Swamp",
    description: "Enter the swamp where bugs lurk. Find broken logic and fix it before the program crashes!",
    color: "bg-destructive",
    icon: "Bug",
    requiredLevel: 6,
    puzzles: debugPuzzles,
    category: "debugging",
  },
]

export const INITIAL_PROGRESS = {
  level: 1,
  xp: 0,
  xpToNextLevel: 100,
  completedPuzzles: [] as string[],
  currentStreak: 0,
  bestStreak: 0,
  badges: [],
  unlockedWorlds: ["sequential"],
}

export const BADGES = [
  { id: "first-solve", name: "First Steps", description: "Complete your first puzzle", icon: "Footprints" },
  { id: "streak-3", name: "On a Roll", description: "Get a 3 puzzle streak", icon: "Flame" },
  { id: "streak-5", name: "Unstoppable", description: "Get a 5 puzzle streak", icon: "Zap" },
  { id: "seq-master", name: "Sequence Master", description: "Complete all sequence puzzles", icon: "ArrowRight" },
  { id: "cond-master", name: "Decision Maker", description: "Complete all conditional puzzles", icon: "GitBranch" },
  { id: "loop-master", name: "Loop Legend", description: "Complete all loop puzzles", icon: "Repeat" },
  { id: "bug-hunter", name: "Bug Hunter", description: "Complete a debugging puzzle", icon: "Bug" },
  { id: "level-5", name: "Rising Star", description: "Reach level 5", icon: "Star" },
  { id: "all-worlds", name: "World Explorer", description: "Unlock all worlds", icon: "Globe" },
]
